### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [MCosta093/0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

i) Faltou fazer o indicativo de qual página está ativa. Além disso, ii) faltou fazer a listagem das tarefas "concluídas" e "excluidas". Por fim, iii) faltou fazer o efeito de `scale` para o item de hover e iv) centralizar o seu conteúdo. 

O indicativo poderia ser obtido com o uso de uma classe extra com efeito de negrito e então a adição dessa classe dentro do arquivo .html que a página está ativa. 

```html
<style>
  .ativo {
    text-weight: bold;
  }
</style>

<a href="pendentes.html" class="ativo pendentes">Pendentes</a>
```

O scale poderia ser obtido através do uso do `:hover` para o seu `tarefas`.

```css
.tarefas {
  transition: transform 0.1s ease-in-out;
}

.tarefas:hover {
    transform: scale(1.1);
}
```

A centralização do conteúdo poderia ser obtido através do uso do `margin`. 

```html
<style>
.conteudo {
  margin: 0 auto;
  width: 50%;
}
</style>

<body class="conteudo">
  <p>Conteudo...</p>
</body>
```

**Nota:** 6

# Comentários

Notei que muitas das suas propriedades CSS são duplicadas entre as classes `pendentes` `concluidas` e `excluidas`. Você poderia criar uma classe mais genérica para armazenar essas propriedades e então fazer uso de duas classes. Veja no exemplo abaixo que é utilizada a classe `link` junto com a classe `pendentes`.

```html
<a href="pendentes.html" class="link pendentes">Pendentes</a>
``` 

O CSS ficaria assim: 

```css
.link {
    min-width: 9rem;
    padding: 0.5rem;
    border-radius: 50rem;
    border: solid 1px #aaa;
    text-align: center;
    text-decoration: none;
    color: white;
    margin: 10px;   
}

.pendentes {
    background-color: #8FD14F;
}

.concluidas {
    background-color: #0CA789;
}

.excluidas {
    background-color: #EB4045;
}
```

Você pode imaginar agora que `tarefa` possui três subvariações: `pendentes`, `concluidas` e `excluidas`.

```mermaid
flowchart LR;
  tarefa --> concluida;
  tarefa --> pendente;
  tarefa --> excluida;
```
